### ISSUE TITLE
Trained model

### ISSUE THREAD

**Issue by samieti02** [mateuszbuda/brain-segmentation#1]
Hello sir,

can we have (or download) a trained model to use to remove the skull ?

Thanks

**Comment by mateuszbuda** [comment]
Hi, thank for your interest in my work.
You can use either the `./download_weights.sh` script or this link: https://docs.google.com/uc?export=download&id=1yfXFngcJvBO3EKuC6-ASboW_TPyLSLgd to get trained model weights for skull stripping.
For more details on required preprocessing and usage, refer to readme file in the [skull-stripping folder](https://github.com/mateuszbuda/brain-segmentation/blob/master/skull-stripping/README.md).
Also, keep in mind that code in this repository comes with a [license](https://github.com/mateuszbuda/brain-segmentation/blob/master/LICENSE).
